# como se declara e inicia el dockerfile

services:
  app-csv:
    build:
      context: .
      #crea un servicio con el nombre app-csv donde construye el archivo dockerfile
      dockerfile: Dockerfile
    # enlaza directamente(:) todos los archivos (.) hacia la carpeta app que se 
    # guarda el contenedor(/app)
    volumes:
      - .:/app
