version: '3'
services: 
  blockchain: 
    build: ./blockchain
    ports:
      - "5000:5000"
    networks:
      - blockchain-network
  wallet:
    build: ./wallet
    ports:
      - "5002:5002"
    networks:
    - blockchain-network
  validator:
    build: ./validator
    ports:
      - "5003:5003"
    networks:
      - blockchain-network
  closerblock:
    build: ./closerblock
    ports:
      - "5004:5004"
    networks:
      - blockchain-network
  middleware:
    build: ./middleware
    ports:
      - "5001:5001"
    networks:
      - blockchain-network
networks:
  blockchain-network:
    driver: bridge